/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuppressionsRouteImport } from './routes/suppressions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesflowsRouteImport } from './routes/salesflows'
import { Route as ReplyAgentRouteImport } from './routes/reply-agent'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MailboxesRouteImport } from './routes/mailboxes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as UnsubscribeLeadIdRouteImport } from './routes/unsubscribe.$leadId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiPublicWarmupTickRouteImport } from './routes/api/public/warmup-tick'
import { Route as ApiPublicVisitorRouteImport } from './routes/api/public/visitor'
import { Route as ApiPublicProcessQueueRouteImport } from './routes/api/public/process-queue'
import { Route as ApiPublicImapSyncRouteImport } from './routes/api/public/imap-sync'
import { Route as ApiPublicVisitorJsRouteImport } from './routes/api/public/visitor.js'
import { Route as ApiPublicUnsubscribeLeadIdRouteImport } from './routes/api/public/unsubscribe.$leadId'
import { Route as ApiPublicInboundSecretRouteImport } from './routes/api/public/inbound.$secret'
import { Route as ApiPublicTrackOpenTrackingIdRouteImport } from './routes/api/public/track.open.$trackingId'
import { Route as ApiPublicTrackClickTrackingIdRouteImport } from './routes/api/public/track.click.$trackingId'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionsRoute = SuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesflowsRoute = SalesflowsRouteImport.update({
  id: '/salesflows',
  path: '/salesflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyAgentRoute = ReplyAgentRouteImport.update({
  id: '/reply-agent',
  path: '/reply-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesRoute = MailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeLeadIdRoute = UnsubscribeLeadIdRouteImport.update({
  id: '/unsubscribe/$leadId',
  path: '/unsubscribe/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWarmupTickRoute = ApiPublicWarmupTickRouteImport.update({
  id: '/api/public/warmup-tick',
  path: '/api/public/warmup-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitorRoute = ApiPublicVisitorRouteImport.update({
  id: '/api/public/visitor',
  path: '/api/public/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessQueueRoute = ApiPublicProcessQueueRouteImport.update({
  id: '/api/public/process-queue',
  path: '/api/public/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImapSyncRoute = ApiPublicImapSyncRouteImport.update({
  id: '/api/public/imap-sync',
  path: '/api/public/imap-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitorJsRoute = ApiPublicVisitorJsRouteImport.update({
  id: '/js',
  path: '/js',
  getParentRoute: () => ApiPublicVisitorRoute,
} as any)
const ApiPublicUnsubscribeLeadIdRoute =
  ApiPublicUnsubscribeLeadIdRouteImport.update({
    id: '/api/public/unsubscribe/$leadId',
    path: '/api/public/unsubscribe/$leadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboundSecretRoute = ApiPublicInboundSecretRouteImport.update({
  id: '/api/public/inbound/$secret',
  path: '/api/public/inbound/$secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackOpenTrackingIdRoute =
  ApiPublicTrackOpenTrackingIdRouteImport.update({
    id: '/api/public/track/open/$trackingId',
    path: '/api/public/track/open/$trackingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackClickTrackingIdRoute =
  ApiPublicTrackClickTrackingIdRouteImport.update({
    id: '/api/public/track/click/$trackingId',
    path: '/api/public/track/click/$trackingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/salesflows': typeof SalesflowsRoute
  '/settings': typeof SettingsRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRouteWithChildren
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/api/public/visitor/js': typeof ApiPublicVisitorJsRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/salesflows': typeof SalesflowsRoute
  '/settings': typeof SettingsRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRouteWithChildren
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/api/public/visitor/js': typeof ApiPublicVisitorJsRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/salesflows': typeof SalesflowsRoute
  '/settings': typeof SettingsRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRouteWithChildren
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/api/public/visitor/js': typeof ApiPublicVisitorJsRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/copilot'
    | '/dashboard'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/onboarding'
    | '/pipeline'
    | '/reply-agent'
    | '/salesflows'
    | '/settings'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/campaigns/'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/warmup-tick'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/api/public/visitor/js'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/copilot'
    | '/dashboard'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/onboarding'
    | '/pipeline'
    | '/reply-agent'
    | '/salesflows'
    | '/settings'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/campaigns'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/warmup-tick'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/api/public/visitor/js'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/copilot'
    | '/dashboard'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/onboarding'
    | '/pipeline'
    | '/reply-agent'
    | '/salesflows'
    | '/settings'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/campaigns/'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/warmup-tick'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/api/public/visitor/js'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MailboxesRoute: typeof MailboxesRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  ReplyAgentRoute: typeof ReplyAgentRoute
  SalesflowsRoute: typeof SalesflowsRoute
  SettingsRoute: typeof SettingsRoute
  SuppressionsRoute: typeof SuppressionsRoute
  TeamRoute: typeof TeamRoute
  VisitorsRoute: typeof VisitorsRoute
  WarmupRoute: typeof WarmupRoute
  WebhooksRoute: typeof WebhooksRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  UnsubscribeLeadIdRoute: typeof UnsubscribeLeadIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ApiPublicImapSyncRoute: typeof ApiPublicImapSyncRoute
  ApiPublicProcessQueueRoute: typeof ApiPublicProcessQueueRoute
  ApiPublicVisitorRoute: typeof ApiPublicVisitorRouteWithChildren
  ApiPublicWarmupTickRoute: typeof ApiPublicWarmupTickRoute
  ApiPublicInboundSecretRoute: typeof ApiPublicInboundSecretRoute
  ApiPublicUnsubscribeLeadIdRoute: typeof ApiPublicUnsubscribeLeadIdRoute
  ApiPublicTrackClickTrackingIdRoute: typeof ApiPublicTrackClickTrackingIdRoute
  ApiPublicTrackOpenTrackingIdRoute: typeof ApiPublicTrackOpenTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppressions': {
      id: '/suppressions'
      path: '/suppressions'
      fullPath: '/suppressions'
      preLoaderRoute: typeof SuppressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesflows': {
      id: '/salesflows'
      path: '/salesflows'
      fullPath: '/salesflows'
      preLoaderRoute: typeof SalesflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply-agent': {
      id: '/reply-agent'
      path: '/reply-agent'
      fullPath: '/reply-agent'
      preLoaderRoute: typeof ReplyAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes': {
      id: '/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof MailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$leadId': {
      id: '/unsubscribe/$leadId'
      path: '/unsubscribe/$leadId'
      fullPath: '/unsubscribe/$leadId'
      preLoaderRoute: typeof UnsubscribeLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/warmup-tick': {
      id: '/api/public/warmup-tick'
      path: '/api/public/warmup-tick'
      fullPath: '/api/public/warmup-tick'
      preLoaderRoute: typeof ApiPublicWarmupTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visitor': {
      id: '/api/public/visitor'
      path: '/api/public/visitor'
      fullPath: '/api/public/visitor'
      preLoaderRoute: typeof ApiPublicVisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-queue': {
      id: '/api/public/process-queue'
      path: '/api/public/process-queue'
      fullPath: '/api/public/process-queue'
      preLoaderRoute: typeof ApiPublicProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/imap-sync': {
      id: '/api/public/imap-sync'
      path: '/api/public/imap-sync'
      fullPath: '/api/public/imap-sync'
      preLoaderRoute: typeof ApiPublicImapSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visitor/js': {
      id: '/api/public/visitor/js'
      path: '/js'
      fullPath: '/api/public/visitor/js'
      preLoaderRoute: typeof ApiPublicVisitorJsRouteImport
      parentRoute: typeof ApiPublicVisitorRoute
    }
    '/api/public/unsubscribe/$leadId': {
      id: '/api/public/unsubscribe/$leadId'
      path: '/api/public/unsubscribe/$leadId'
      fullPath: '/api/public/unsubscribe/$leadId'
      preLoaderRoute: typeof ApiPublicUnsubscribeLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound/$secret': {
      id: '/api/public/inbound/$secret'
      path: '/api/public/inbound/$secret'
      fullPath: '/api/public/inbound/$secret'
      preLoaderRoute: typeof ApiPublicInboundSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$trackingId': {
      id: '/api/public/track/open/$trackingId'
      path: '/api/public/track/open/$trackingId'
      fullPath: '/api/public/track/open/$trackingId'
      preLoaderRoute: typeof ApiPublicTrackOpenTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click/$trackingId': {
      id: '/api/public/track/click/$trackingId'
      path: '/api/public/track/click/$trackingId'
      fullPath: '/api/public/track/click/$trackingId'
      preLoaderRoute: typeof ApiPublicTrackClickTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicVisitorRouteChildren {
  ApiPublicVisitorJsRoute: typeof ApiPublicVisitorJsRoute
}

const ApiPublicVisitorRouteChildren: ApiPublicVisitorRouteChildren = {
  ApiPublicVisitorJsRoute: ApiPublicVisitorJsRoute,
}

const ApiPublicVisitorRouteWithChildren =
  ApiPublicVisitorRoute._addFileChildren(ApiPublicVisitorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MailboxesRoute: MailboxesRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  ReplyAgentRoute: ReplyAgentRoute,
  SalesflowsRoute: SalesflowsRoute,
  SettingsRoute: SettingsRoute,
  SuppressionsRoute: SuppressionsRoute,
  TeamRoute: TeamRoute,
  VisitorsRoute: VisitorsRoute,
  WarmupRoute: WarmupRoute,
  WebhooksRoute: WebhooksRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  UnsubscribeLeadIdRoute: UnsubscribeLeadIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ApiPublicImapSyncRoute: ApiPublicImapSyncRoute,
  ApiPublicProcessQueueRoute: ApiPublicProcessQueueRoute,
  ApiPublicVisitorRoute: ApiPublicVisitorRouteWithChildren,
  ApiPublicWarmupTickRoute: ApiPublicWarmupTickRoute,
  ApiPublicInboundSecretRoute: ApiPublicInboundSecretRoute,
  ApiPublicUnsubscribeLeadIdRoute: ApiPublicUnsubscribeLeadIdRoute,
  ApiPublicTrackClickTrackingIdRoute: ApiPublicTrackClickTrackingIdRoute,
  ApiPublicTrackOpenTrackingIdRoute: ApiPublicTrackOpenTrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
