/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WarmupRouteImport } from './routes/warmup'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuppressionsRouteImport } from './routes/suppressions'
import { Route as SubsequencesRouteImport } from './routes/subsequences'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SequenceBlueprintRouteImport } from './routes/sequence-blueprint'
import { Route as SalesflowsRouteImport } from './routes/salesflows'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplyRateFormulaRouteImport } from './routes/reply-rate-formula'
import { Route as ReplyAgentRouteImport } from './routes/reply-agent'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MailboxesRouteImport } from './routes/mailboxes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DeliverabilityBibleRouteImport } from './routes/deliverability-bible'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminnRouteImport } from './routes/adminn'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R47TemplatesRouteImport } from './routes/47-templates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VsSmartleadRouteImport } from './routes/vs.smartlead'
import { Route as VsLemlistRouteImport } from './routes/vs.lemlist'
import { Route as VsInstantlyRouteImport } from './routes/vs.instantly'
import { Route as UnsubscribeLeadIdRouteImport } from './routes/unsubscribe.$leadId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminMailboxesRouteImport } from './routes/admin.mailboxes'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminDeliverabilityRouteImport } from './routes/admin.deliverability'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAcceptInviteRouteImport } from './routes/admin.accept-invite'
import { Route as AdminIntegrationsIndexRouteImport } from './routes/admin.integrations.index'
import { Route as ApiPublicWarmupTickRouteImport } from './routes/api/public/warmup-tick'
import { Route as ApiPublicVisitorDotjsRouteImport } from './routes/api/public/visitor[.]js'
import { Route as ApiPublicVisitorRouteImport } from './routes/api/public/visitor'
import { Route as ApiPublicProcessQueueRouteImport } from './routes/api/public/process-queue'
import { Route as ApiPublicImapSyncRouteImport } from './routes/api/public/imap-sync'
import { Route as ApiPublicGhlWebhookRouteImport } from './routes/api/public/ghl-webhook'
import { Route as AdminViewAsUserIdRouteImport } from './routes/admin.view-as.$userId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminIntegrationsGhlRouteImport } from './routes/admin.integrations.ghl'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicUnsubscribeLeadIdRouteImport } from './routes/api/public/unsubscribe.$leadId'
import { Route as ApiPublicInboundSecretRouteImport } from './routes/api/public/inbound.$secret'
import { Route as ApiPublicTrackOpenTrackingIdRouteImport } from './routes/api/public/track.open.$trackingId'
import { Route as ApiPublicTrackClickTrackingIdRouteImport } from './routes/api/public/track.click.$trackingId'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WarmupRoute = WarmupRouteImport.update({
  id: '/warmup',
  path: '/warmup',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionsRoute = SuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsequencesRoute = SubsequencesRouteImport.update({
  id: '/subsequences',
  path: '/subsequences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SequenceBlueprintRoute = SequenceBlueprintRouteImport.update({
  id: '/sequence-blueprint',
  path: '/sequence-blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesflowsRoute = SalesflowsRouteImport.update({
  id: '/salesflows',
  path: '/salesflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyRateFormulaRoute = ReplyRateFormulaRouteImport.update({
  id: '/reply-rate-formula',
  path: '/reply-rate-formula',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyAgentRoute = ReplyAgentRouteImport.update({
  id: '/reply-agent',
  path: '/reply-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesRoute = MailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverabilityBibleRoute = DeliverabilityBibleRouteImport.update({
  id: '/deliverability-bible',
  path: '/deliverability-bible',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminnRoute = AdminnRouteImport.update({
  id: '/adminn',
  path: '/adminn',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R47TemplatesRoute = R47TemplatesRouteImport.update({
  id: '/47-templates',
  path: '/47-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSmartleadRoute = VsSmartleadRouteImport.update({
  id: '/vs/smartlead',
  path: '/vs/smartlead',
  getParentRoute: () => rootRouteImport,
} as any)
const VsLemlistRoute = VsLemlistRouteImport.update({
  id: '/vs/lemlist',
  path: '/vs/lemlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VsInstantlyRoute = VsInstantlyRouteImport.update({
  id: '/vs/instantly',
  path: '/vs/instantly',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeLeadIdRoute = UnsubscribeLeadIdRouteImport.update({
  id: '/unsubscribe/$leadId',
  path: '/unsubscribe/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/admin/workspaces',
  path: '/admin/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/admin/visitors',
  path: '/admin/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/admin/rbac',
  path: '/admin/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMailboxesRoute = AdminMailboxesRouteImport.update({
  id: '/admin/mailboxes',
  path: '/admin/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliverabilityRoute = AdminDeliverabilityRouteImport.update({
  id: '/admin/deliverability',
  path: '/admin/deliverability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/admin/compliance',
  path: '/admin/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcceptInviteRoute = AdminAcceptInviteRouteImport.update({
  id: '/admin/accept-invite',
  path: '/admin/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminIntegrationsRoute,
} as any)
const ApiPublicWarmupTickRoute = ApiPublicWarmupTickRouteImport.update({
  id: '/api/public/warmup-tick',
  path: '/api/public/warmup-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitorDotjsRoute = ApiPublicVisitorDotjsRouteImport.update({
  id: '/api/public/visitor.js',
  path: '/api/public/visitor.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVisitorRoute = ApiPublicVisitorRouteImport.update({
  id: '/api/public/visitor',
  path: '/api/public/visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessQueueRoute = ApiPublicProcessQueueRouteImport.update({
  id: '/api/public/process-queue',
  path: '/api/public/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImapSyncRoute = ApiPublicImapSyncRouteImport.update({
  id: '/api/public/imap-sync',
  path: '/api/public/imap-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGhlWebhookRoute = ApiPublicGhlWebhookRouteImport.update({
  id: '/api/public/ghl-webhook',
  path: '/api/public/ghl-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewAsUserIdRoute = AdminViewAsUserIdRouteImport.update({
  id: '/admin/view-as/$userId',
  path: '/admin/view-as/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminIntegrationsGhlRoute = AdminIntegrationsGhlRouteImport.update({
  id: '/ghl',
  path: '/ghl',
  getParentRoute: () => AdminIntegrationsRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUnsubscribeLeadIdRoute =
  ApiPublicUnsubscribeLeadIdRouteImport.update({
    id: '/api/public/unsubscribe/$leadId',
    path: '/api/public/unsubscribe/$leadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInboundSecretRoute = ApiPublicInboundSecretRouteImport.update({
  id: '/api/public/inbound/$secret',
  path: '/api/public/inbound/$secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackOpenTrackingIdRoute =
  ApiPublicTrackOpenTrackingIdRouteImport.update({
    id: '/api/public/track/open/$trackingId',
    path: '/api/public/track/open/$trackingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackClickTrackingIdRoute =
  ApiPublicTrackClickTrackingIdRouteImport.update({
    id: '/api/public/track/click/$trackingId',
    path: '/api/public/track/click/$trackingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/47-templates': typeof R47TemplatesRoute
  '/about': typeof AboutRoute
  '/adminn': typeof AdminnRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/deliverability-bible': typeof DeliverabilityBibleRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/reply-rate-formula': typeof ReplyRateFormulaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/salesflows': typeof SalesflowsRoute
  '/sequence-blueprint': typeof SequenceBlueprintRoute
  '/settings': typeof SettingsRoute
  '/subsequences': typeof SubsequencesRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/deliverability': typeof AdminDeliverabilityRoute
  '/admin/integrations': typeof AdminIntegrationsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/vs/instantly': typeof VsInstantlyRoute
  '/vs/lemlist': typeof VsLemlistRoute
  '/vs/smartlead': typeof VsSmartleadRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/admin/integrations/ghl': typeof AdminIntegrationsGhlRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/view-as/$userId': typeof AdminViewAsUserIdRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRoute
  '/api/public/visitor.js': typeof ApiPublicVisitorDotjsRoute
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/47-templates': typeof R47TemplatesRoute
  '/about': typeof AboutRoute
  '/adminn': typeof AdminnRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/deliverability-bible': typeof DeliverabilityBibleRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/reply-rate-formula': typeof ReplyRateFormulaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/salesflows': typeof SalesflowsRoute
  '/sequence-blueprint': typeof SequenceBlueprintRoute
  '/settings': typeof SettingsRoute
  '/subsequences': typeof SubsequencesRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/deliverability': typeof AdminDeliverabilityRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/vs/instantly': typeof VsInstantlyRoute
  '/vs/lemlist': typeof VsLemlistRoute
  '/vs/smartlead': typeof VsSmartleadRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/admin/integrations/ghl': typeof AdminIntegrationsGhlRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/view-as/$userId': typeof AdminViewAsUserIdRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRoute
  '/api/public/visitor.js': typeof ApiPublicVisitorDotjsRoute
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/47-templates': typeof R47TemplatesRoute
  '/about': typeof AboutRoute
  '/adminn': typeof AdminnRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/deliverability-bible': typeof DeliverabilityBibleRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/inbox': typeof InboxRoute
  '/leads': typeof LeadsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mailboxes': typeof MailboxesRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/reply-agent': typeof ReplyAgentRoute
  '/reply-rate-formula': typeof ReplyRateFormulaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/salesflows': typeof SalesflowsRoute
  '/sequence-blueprint': typeof SequenceBlueprintRoute
  '/settings': typeof SettingsRoute
  '/subsequences': typeof SubsequencesRoute
  '/suppressions': typeof SuppressionsRoute
  '/team': typeof TeamRoute
  '/visitors': typeof VisitorsRoute
  '/warmup': typeof WarmupRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/deliverability': typeof AdminDeliverabilityRoute
  '/admin/integrations': typeof AdminIntegrationsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/mailboxes': typeof AdminMailboxesRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/unsubscribe/$leadId': typeof UnsubscribeLeadIdRoute
  '/vs/instantly': typeof VsInstantlyRoute
  '/vs/lemlist': typeof VsLemlistRoute
  '/vs/smartlead': typeof VsSmartleadRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/admin/integrations/ghl': typeof AdminIntegrationsGhlRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/view-as/$userId': typeof AdminViewAsUserIdRoute
  '/api/public/ghl-webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/imap-sync': typeof ApiPublicImapSyncRoute
  '/api/public/process-queue': typeof ApiPublicProcessQueueRoute
  '/api/public/visitor': typeof ApiPublicVisitorRoute
  '/api/public/visitor.js': typeof ApiPublicVisitorDotjsRoute
  '/api/public/warmup-tick': typeof ApiPublicWarmupTickRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/api/public/inbound/$secret': typeof ApiPublicInboundSecretRoute
  '/api/public/unsubscribe/$leadId': typeof ApiPublicUnsubscribeLeadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/track/click/$trackingId': typeof ApiPublicTrackClickTrackingIdRoute
  '/api/public/track/open/$trackingId': typeof ApiPublicTrackOpenTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/47-templates'
    | '/about'
    | '/adminn'
    | '/analytics'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/deliverability-bible'
    | '/features'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/meetings'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/reply-agent'
    | '/reply-rate-formula'
    | '/reset-password'
    | '/resources'
    | '/salesflows'
    | '/sequence-blueprint'
    | '/settings'
    | '/subsequences'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/admin/accept-invite'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/compliance'
    | '/admin/content'
    | '/admin/credits'
    | '/admin/deliverability'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/mailboxes'
    | '/admin/rbac'
    | '/admin/support'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/workspaces'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/vs/instantly'
    | '/vs/lemlist'
    | '/vs/smartlead'
    | '/admin/'
    | '/campaigns/'
    | '/admin/integrations/ghl'
    | '/admin/users/$userId'
    | '/admin/view-as/$userId'
    | '/api/public/ghl-webhook'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/visitor.js'
    | '/api/public/warmup-tick'
    | '/admin/integrations/'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/lovable/email/queue/process'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/47-templates'
    | '/about'
    | '/adminn'
    | '/analytics'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/deliverability-bible'
    | '/features'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/meetings'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/reply-agent'
    | '/reply-rate-formula'
    | '/reset-password'
    | '/resources'
    | '/salesflows'
    | '/sequence-blueprint'
    | '/settings'
    | '/subsequences'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/admin/accept-invite'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/compliance'
    | '/admin/content'
    | '/admin/credits'
    | '/admin/deliverability'
    | '/admin/leads'
    | '/admin/mailboxes'
    | '/admin/rbac'
    | '/admin/support'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/workspaces'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/vs/instantly'
    | '/vs/lemlist'
    | '/vs/smartlead'
    | '/admin'
    | '/campaigns'
    | '/admin/integrations/ghl'
    | '/admin/users/$userId'
    | '/admin/view-as/$userId'
    | '/api/public/ghl-webhook'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/visitor.js'
    | '/api/public/warmup-tick'
    | '/admin/integrations'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/lovable/email/queue/process'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  id:
    | '__root__'
    | '/'
    | '/47-templates'
    | '/about'
    | '/adminn'
    | '/analytics'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/deliverability-bible'
    | '/features'
    | '/goals'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/login'
    | '/mailboxes'
    | '/meetings'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/reply-agent'
    | '/reply-rate-formula'
    | '/reset-password'
    | '/resources'
    | '/salesflows'
    | '/sequence-blueprint'
    | '/settings'
    | '/subsequences'
    | '/suppressions'
    | '/team'
    | '/visitors'
    | '/warmup'
    | '/webhooks'
    | '/admin/accept-invite'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/compliance'
    | '/admin/content'
    | '/admin/credits'
    | '/admin/deliverability'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/mailboxes'
    | '/admin/rbac'
    | '/admin/support'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/workspaces'
    | '/campaigns/$id'
    | '/invite/$token'
    | '/unsubscribe/$leadId'
    | '/vs/instantly'
    | '/vs/lemlist'
    | '/vs/smartlead'
    | '/admin/'
    | '/campaigns/'
    | '/admin/integrations/ghl'
    | '/admin/users/$userId'
    | '/admin/view-as/$userId'
    | '/api/public/ghl-webhook'
    | '/api/public/imap-sync'
    | '/api/public/process-queue'
    | '/api/public/visitor'
    | '/api/public/visitor.js'
    | '/api/public/warmup-tick'
    | '/admin/integrations/'
    | '/api/public/inbound/$secret'
    | '/api/public/unsubscribe/$leadId'
    | '/lovable/email/queue/process'
    | '/api/public/track/click/$trackingId'
    | '/api/public/track/open/$trackingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R47TemplatesRoute: typeof R47TemplatesRoute
  AboutRoute: typeof AboutRoute
  AdminnRoute: typeof AdminnRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DeliverabilityBibleRoute: typeof DeliverabilityBibleRoute
  FeaturesRoute: typeof FeaturesRoute
  GoalsRoute: typeof GoalsRoute
  InboxRoute: typeof InboxRoute
  LeadsRoute: typeof LeadsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MailboxesRoute: typeof MailboxesRoute
  MeetingsRoute: typeof MeetingsRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  ReplyAgentRoute: typeof ReplyAgentRoute
  ReplyRateFormulaRoute: typeof ReplyRateFormulaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SalesflowsRoute: typeof SalesflowsRoute
  SequenceBlueprintRoute: typeof SequenceBlueprintRoute
  SettingsRoute: typeof SettingsRoute
  SubsequencesRoute: typeof SubsequencesRoute
  SuppressionsRoute: typeof SuppressionsRoute
  TeamRoute: typeof TeamRoute
  VisitorsRoute: typeof VisitorsRoute
  WarmupRoute: typeof WarmupRoute
  WebhooksRoute: typeof WebhooksRoute
  AdminAcceptInviteRoute: typeof AdminAcceptInviteRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminDeliverabilityRoute: typeof AdminDeliverabilityRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMailboxesRoute: typeof AdminMailboxesRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  UnsubscribeLeadIdRoute: typeof UnsubscribeLeadIdRoute
  VsInstantlyRoute: typeof VsInstantlyRoute
  VsLemlistRoute: typeof VsLemlistRoute
  VsSmartleadRoute: typeof VsSmartleadRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  AdminViewAsUserIdRoute: typeof AdminViewAsUserIdRoute
  ApiPublicGhlWebhookRoute: typeof ApiPublicGhlWebhookRoute
  ApiPublicImapSyncRoute: typeof ApiPublicImapSyncRoute
  ApiPublicProcessQueueRoute: typeof ApiPublicProcessQueueRoute
  ApiPublicVisitorRoute: typeof ApiPublicVisitorRoute
  ApiPublicVisitorDotjsRoute: typeof ApiPublicVisitorDotjsRoute
  ApiPublicWarmupTickRoute: typeof ApiPublicWarmupTickRoute
  ApiPublicInboundSecretRoute: typeof ApiPublicInboundSecretRoute
  ApiPublicUnsubscribeLeadIdRoute: typeof ApiPublicUnsubscribeLeadIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicTrackClickTrackingIdRoute: typeof ApiPublicTrackClickTrackingIdRoute
  ApiPublicTrackOpenTrackingIdRoute: typeof ApiPublicTrackOpenTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warmup': {
      id: '/warmup'
      path: '/warmup'
      fullPath: '/warmup'
      preLoaderRoute: typeof WarmupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppressions': {
      id: '/suppressions'
      path: '/suppressions'
      fullPath: '/suppressions'
      preLoaderRoute: typeof SuppressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subsequences': {
      id: '/subsequences'
      path: '/subsequences'
      fullPath: '/subsequences'
      preLoaderRoute: typeof SubsequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequence-blueprint': {
      id: '/sequence-blueprint'
      path: '/sequence-blueprint'
      fullPath: '/sequence-blueprint'
      preLoaderRoute: typeof SequenceBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesflows': {
      id: '/salesflows'
      path: '/salesflows'
      fullPath: '/salesflows'
      preLoaderRoute: typeof SalesflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply-rate-formula': {
      id: '/reply-rate-formula'
      path: '/reply-rate-formula'
      fullPath: '/reply-rate-formula'
      preLoaderRoute: typeof ReplyRateFormulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply-agent': {
      id: '/reply-agent'
      path: '/reply-agent'
      fullPath: '/reply-agent'
      preLoaderRoute: typeof ReplyAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes': {
      id: '/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof MailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliverability-bible': {
      id: '/deliverability-bible'
      path: '/deliverability-bible'
      fullPath: '/deliverability-bible'
      preLoaderRoute: typeof DeliverabilityBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminn': {
      id: '/adminn'
      path: '/adminn'
      fullPath: '/adminn'
      preLoaderRoute: typeof AdminnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/47-templates': {
      id: '/47-templates'
      path: '/47-templates'
      fullPath: '/47-templates'
      preLoaderRoute: typeof R47TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/smartlead': {
      id: '/vs/smartlead'
      path: '/vs/smartlead'
      fullPath: '/vs/smartlead'
      preLoaderRoute: typeof VsSmartleadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/lemlist': {
      id: '/vs/lemlist'
      path: '/vs/lemlist'
      fullPath: '/vs/lemlist'
      preLoaderRoute: typeof VsLemlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/instantly': {
      id: '/vs/instantly'
      path: '/vs/instantly'
      fullPath: '/vs/instantly'
      preLoaderRoute: typeof VsInstantlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$leadId': {
      id: '/unsubscribe/$leadId'
      path: '/unsubscribe/$leadId'
      fullPath: '/unsubscribe/$leadId'
      preLoaderRoute: typeof UnsubscribeLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/admin/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mailboxes': {
      id: '/admin/mailboxes'
      path: '/admin/mailboxes'
      fullPath: '/admin/mailboxes'
      preLoaderRoute: typeof AdminMailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliverability': {
      id: '/admin/deliverability'
      path: '/admin/deliverability'
      fullPath: '/admin/deliverability'
      preLoaderRoute: typeof AdminDeliverabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accept-invite': {
      id: '/admin/accept-invite'
      path: '/admin/accept-invite'
      fullPath: '/admin/accept-invite'
      preLoaderRoute: typeof AdminAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof AdminIntegrationsRoute
    }
    '/api/public/warmup-tick': {
      id: '/api/public/warmup-tick'
      path: '/api/public/warmup-tick'
      fullPath: '/api/public/warmup-tick'
      preLoaderRoute: typeof ApiPublicWarmupTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visitor.js': {
      id: '/api/public/visitor.js'
      path: '/api/public/visitor.js'
      fullPath: '/api/public/visitor.js'
      preLoaderRoute: typeof ApiPublicVisitorDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/visitor': {
      id: '/api/public/visitor'
      path: '/api/public/visitor'
      fullPath: '/api/public/visitor'
      preLoaderRoute: typeof ApiPublicVisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-queue': {
      id: '/api/public/process-queue'
      path: '/api/public/process-queue'
      fullPath: '/api/public/process-queue'
      preLoaderRoute: typeof ApiPublicProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/imap-sync': {
      id: '/api/public/imap-sync'
      path: '/api/public/imap-sync'
      fullPath: '/api/public/imap-sync'
      preLoaderRoute: typeof ApiPublicImapSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl-webhook': {
      id: '/api/public/ghl-webhook'
      path: '/api/public/ghl-webhook'
      fullPath: '/api/public/ghl-webhook'
      preLoaderRoute: typeof ApiPublicGhlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view-as/$userId': {
      id: '/admin/view-as/$userId'
      path: '/admin/view-as/$userId'
      fullPath: '/admin/view-as/$userId'
      preLoaderRoute: typeof AdminViewAsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/integrations/ghl': {
      id: '/admin/integrations/ghl'
      path: '/ghl'
      fullPath: '/admin/integrations/ghl'
      preLoaderRoute: typeof AdminIntegrationsGhlRouteImport
      parentRoute: typeof AdminIntegrationsRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe/$leadId': {
      id: '/api/public/unsubscribe/$leadId'
      path: '/api/public/unsubscribe/$leadId'
      fullPath: '/api/public/unsubscribe/$leadId'
      preLoaderRoute: typeof ApiPublicUnsubscribeLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound/$secret': {
      id: '/api/public/inbound/$secret'
      path: '/api/public/inbound/$secret'
      fullPath: '/api/public/inbound/$secret'
      preLoaderRoute: typeof ApiPublicInboundSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$trackingId': {
      id: '/api/public/track/open/$trackingId'
      path: '/api/public/track/open/$trackingId'
      fullPath: '/api/public/track/open/$trackingId'
      preLoaderRoute: typeof ApiPublicTrackOpenTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click/$trackingId': {
      id: '/api/public/track/click/$trackingId'
      path: '/api/public/track/click/$trackingId'
      fullPath: '/api/public/track/click/$trackingId'
      preLoaderRoute: typeof ApiPublicTrackClickTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminIntegrationsRouteChildren {
  AdminIntegrationsGhlRoute: typeof AdminIntegrationsGhlRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
}

const AdminIntegrationsRouteChildren: AdminIntegrationsRouteChildren = {
  AdminIntegrationsGhlRoute: AdminIntegrationsGhlRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
}

const AdminIntegrationsRouteWithChildren =
  AdminIntegrationsRoute._addFileChildren(AdminIntegrationsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R47TemplatesRoute: R47TemplatesRoute,
  AboutRoute: AboutRoute,
  AdminnRoute: AdminnRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DeliverabilityBibleRoute: DeliverabilityBibleRoute,
  FeaturesRoute: FeaturesRoute,
  GoalsRoute: GoalsRoute,
  InboxRoute: InboxRoute,
  LeadsRoute: LeadsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MailboxesRoute: MailboxesRoute,
  MeetingsRoute: MeetingsRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  ReplyAgentRoute: ReplyAgentRoute,
  ReplyRateFormulaRoute: ReplyRateFormulaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SalesflowsRoute: SalesflowsRoute,
  SequenceBlueprintRoute: SequenceBlueprintRoute,
  SettingsRoute: SettingsRoute,
  SubsequencesRoute: SubsequencesRoute,
  SuppressionsRoute: SuppressionsRoute,
  TeamRoute: TeamRoute,
  VisitorsRoute: VisitorsRoute,
  WarmupRoute: WarmupRoute,
  WebhooksRoute: WebhooksRoute,
  AdminAcceptInviteRoute: AdminAcceptInviteRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminDeliverabilityRoute: AdminDeliverabilityRoute,
  AdminIntegrationsRoute: AdminIntegrationsRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMailboxesRoute: AdminMailboxesRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  UnsubscribeLeadIdRoute: UnsubscribeLeadIdRoute,
  VsInstantlyRoute: VsInstantlyRoute,
  VsLemlistRoute: VsLemlistRoute,
  VsSmartleadRoute: VsSmartleadRoute,
  AdminIndexRoute: AdminIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  AdminViewAsUserIdRoute: AdminViewAsUserIdRoute,
  ApiPublicGhlWebhookRoute: ApiPublicGhlWebhookRoute,
  ApiPublicImapSyncRoute: ApiPublicImapSyncRoute,
  ApiPublicProcessQueueRoute: ApiPublicProcessQueueRoute,
  ApiPublicVisitorRoute: ApiPublicVisitorRoute,
  ApiPublicVisitorDotjsRoute: ApiPublicVisitorDotjsRoute,
  ApiPublicWarmupTickRoute: ApiPublicWarmupTickRoute,
  ApiPublicInboundSecretRoute: ApiPublicInboundSecretRoute,
  ApiPublicUnsubscribeLeadIdRoute: ApiPublicUnsubscribeLeadIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicTrackClickTrackingIdRoute: ApiPublicTrackClickTrackingIdRoute,
  ApiPublicTrackOpenTrackingIdRoute: ApiPublicTrackOpenTrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
